[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/home/ubuntu/bottle-crm/venv/bin/gunicorn crm.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]

[environments.pr]